# Generated by Django 5.0.2 on 2024-02-25 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Título')),
                ('intro', models.TextField(max_length=512, verbose_name='Introdução')),
                ('content', models.TextField(verbose_name='Conteúdo')),
                ('pub_date', models.DateField(auto_now_add=True, verbose_name='Data de publicação')),
                ('edit_date', models.DateField(auto_now=True, verbose_name='Data de edição')),
                ('author', models.CharField(max_length=32, verbose_name='Autor')),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
    ]
