# Generated by Django 5.0.3 on 2024-03-14 12:02

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('title', models.CharField(max_length=64, verbose_name='Título')),
                ('intro', models.TextField(max_length=512, verbose_name='Introdução')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Conteúdo')),
                ('pub_date', models.DateField(auto_now_add=True, verbose_name='Data de publicação')),
                ('edit_date', models.DateField(auto_now=True, verbose_name='Data de edição')),
                ('author', models.CharField(max_length=32, verbose_name='Autor')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
        ),
    ]
