# Generated by Django 5.0.3 on 2024-03-13 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='assunto',
            new_name='subject',
        ),
    ]
