# Generated by Django 5.0.3 on 2024-03-04 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='home_picture',
            field=models.ImageField(upload_to='', verbose_name='Foto da home page'),
        ),
    ]
